# Where to write Cell Ranger ATAC outputs
out_root: "snake_outs"

# blackilsited reference genome for Cell Ranger ATAC
reference: "/home/l2825/atac_practice/reference/GRCh38_cellranger_mkref"

# One entry per timepoint/sample (folder names under fastq_root)
samples:
  - fastqs_A10
  - fastqs_A9

path_to_fastqs: "/home/l2825/SM012/Raw_fastqs"

#list of Seurat input files
seurat_inputs:
  - "filtered_peak_bc_matrix.h5"
  - "singlecell.csv"
  - "fragments.tsv.gz"
  - "fragments.tsv.gz.tbi"