# Root directory that contains one folder per timepoint with demultiplexed FASTQs
fastq_root: "Raw_fastqs"

# Where to write Cell Ranger ATAC outputs
out_root: "CR_outs"

# blackilsited reference genome for Cell Ranger ATAC
reference: "/home/l2825/atac_practice/reference/masked_genome.fa"

# One entry per timepoint/sample (folder names under fastq_root)
samples:
  - fastqs_A10
  - fastqs_A9

#list of Seurat input files
seurat_inputs:
  - "filtered_peak_bc_matrix.h5"
  - "singlecell.csv"
  - "fragments.tsv.gz"
  - "fragments.tsv.gz.tbi"